# Generated by Django 2.0.3 on 2018-03-17 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alocacacaodisciplinasemdepartamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'alocacacaodisciplinasemdepartamento',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('datanascimento', models.DateTimeField(blank=True, db_column='dataNascimento', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'aluno',
            },
        ),
        migrations.CreateModel(
            name='Blocoequivalencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'blocoequivalencia',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('sigla', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='CursoDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'curso_disciplina',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('sigla', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidadecreditos', models.IntegerField(blank=True, db_column='quantidadeCreditos', null=True)),
                ('cargahoraria', models.IntegerField(db_column='cargaHoraria')),
                ('ehoptativa', models.TextField(blank=True, db_column='ehOptativa', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='Historicoescolar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'historicoescolar',
            },
        ),
        migrations.CreateModel(
            name='Itemhistoricoescolar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('periodo', models.IntegerField(blank=True, null=True)),
                ('situacao', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'itemhistoricoescolar',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='Tabelaequivalencias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'tabelaequivalencias',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('periodo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'turma',
            },
        ),
        migrations.CreateModel(
            name='Versaocurso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cargahorariaminoptativas', models.TextField(blank=True, db_column='cargaHorariaMinOptativas', null=True)),
                ('numero', models.CharField(blank=True, max_length=255, null=True)),
                ('qtdperiodominimo', models.IntegerField(blank=True, db_column='qtdPeriodoMinimo', null=True)),
                ('situacao', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'versaocurso',
            },
        ),
        migrations.CreateModel(
            name='DepartamentoDisciplina',
            fields=[
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sca.Departamento')),
            ],
            options={
                'managed': False,
                'db_table': 'departamento_disciplina',
            },
        ),
        migrations.CreateModel(
            name='DepartamentoProfessor',
            fields=[
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sca.Departamento')),
            ],
            options={
                'managed': False,
                'db_table': 'departamento_professor',
            },
        ),
        migrations.CreateModel(
            name='DisciplinasEquivalentes',
            fields=[
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sca.Blocoequivalencia')),
            ],
            options={
                'managed': False,
                'db_table': 'disciplinas_equivalentes',
            },
        ),
        migrations.CreateModel(
            name='DisciplinasOriginais',
            fields=[
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sca.Blocoequivalencia')),
            ],
            options={
                'managed': False,
                'db_table': 'disciplinas_originais',
            },
        ),
        migrations.CreateModel(
            name='ProfessorDisciplina',
            fields=[
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sca.Professor')),
            ],
            options={
                'managed': False,
                'db_table': 'professor_disciplina',
            },
        ),
        migrations.CreateModel(
            name='TabelaequivalenciasBlocoequivalencia',
            fields=[
                ('tabelaequivalencias', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sca.Tabelaequivalencias')),
            ],
            options={
                'managed': False,
                'db_table': 'tabelaequivalencias_blocoequivalencia',
            },
        ),
        migrations.CreateModel(
            name='VersaocursoTabelaequivalencias',
            fields=[
                ('versaocurso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sca.Versaocurso')),
            ],
            options={
                'managed': False,
                'db_table': 'versaocurso_tabelaequivalencias',
            },
        ),
    ]
