# Generated by Django 2.0.4 on 2018-06-17 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sca', '0001_initial'),
    ]

    operations = [
    ]
