# Generated by Django 2.0.6 on 2018-09-15 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sca', '0002_auto_20180713_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alocacacaodisciplinasemdepartamento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='aluno',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='atividadecomplementar',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='blocoequivalencia',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cursodisciplina',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='departamentodisciplina',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='departamentoprofessor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='disciplinaprereqs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='disciplinasequivalentes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='disciplinasoriginais',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='historicoescolar',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='inscricao',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='itemhistoricoescolar',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notafinal',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='professordisciplina',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='registroatividadecomplementar',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tabelaatividadescomplementares',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tabelaatividadescomplementaresatividadecomplementar',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tabelaequivalencias',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tabelaequivalenciasblocoequivalencia',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipoatividadecomplementar',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='useruserprofile',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='versaocurso',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='versaocursotabelaequivalencias',
            options={'managed': False},
        ),
    ]
