# Generated by Django 2.0.4 on 2018-06-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametros',
            old_name='qtdperiodoslaranja',
            new_name='qtdperiodosfinallaranja',
        ),
        migrations.AddField(
            model_name='parametros',
            name='qtdperiodosiniciallaranja',
            field=models.CharField(default='2 * N', max_length=10),
        ),
    ]
