# Generated by Django 2.0.4 on 2018-06-24 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadd', '0002_auto_20180622_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=255)),
                ('idusuario', models.BigIntegerField()),
                ('itenspagina', models.PositiveSmallIntegerField(choices=[(None, 'Selecione o total de itens por página'), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50)], default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'db_table': 'perfil',
            },
        ),
        migrations.RemoveField(
            model_name='parametros',
            name='defaultitensporpagina',
        ),
        migrations.AlterField(
            model_name='itemhorario',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadd.Horario'),
        ),
    ]
