# Generated by Django 2.0.6 on 2018-06-27 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadd', '0006_auto_20180627_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='comissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membro_comissao', to='cadd.Comissao'),
        ),
    ]
