# Generated by Django 2.0.4 on 2018-04-27 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sca.Curso')),
            ],
            options={
                'managed': True,
                'db_table': 'comissao',
            },
        ),
        migrations.CreateModel(
            name='Convocacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envioemail', models.BooleanField(verbose_name='Email')),
                ('presente', models.BooleanField(verbose_name='Presente')),
                ('anotacao', models.TextField(blank=True, null=True, verbose_name='Anotação')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sca.Aluno')),
            ],
            options={
                'managed': True,
                'db_table': 'convocacao',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('periodo', models.PositiveSmallIntegerField(choices=[(1, '1º semestre'), (2, '2º semestre')], default=1, verbose_name='Período')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('indice', models.FileField(max_length=50, upload_to='', verbose_name='Índice')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sca.Aluno')),
            ],
            options={
                'managed': True,
                'db_table': 'documento',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('periodo', models.PositiveSmallIntegerField(choices=[(1, '1º semestre'), (2, '2º semestre')], default=1, verbose_name='Período')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sca.Curso')),
            ],
            options={
                'managed': True,
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='ItemHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=3, verbose_name='Período')),
                ('diasemana', models.PositiveSmallIntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], verbose_name='Dia da semana')),
                ('inicio', models.TimeField(verbose_name='Início')),
                ('fim', models.TimeField(verbose_name='Início')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sca.Departamento')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sca.Disciplina')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadd.Horario')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sca.Professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sca.Turma')),
            ],
            options={
                'managed': True,
                'db_table': 'item_horario',
            },
        ),
        migrations.CreateModel(
            name='ItemPlanoAtual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemhorario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadd.ItemHorario')),
            ],
            options={
                'managed': True,
                'db_table': 'item_plano_atual',
            },
        ),
        migrations.CreateModel(
            name='ItemPlanoFuturo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sca.Disciplina')),
            ],
            options={
                'managed': True,
                'db_table': 'item_plano_futuro',
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(verbose_name='Ativo')),
                ('presidente', models.BooleanField(verbose_name='Presidente')),
                ('portaria', models.CharField(max_length=50, verbose_name='Portaria')),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadd.Comissao')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sca.Professor')),
            ],
            options={
                'managed': True,
                'db_table': 'membro',
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('periodo', models.PositiveSmallIntegerField(choices=[(1, '1º semestre'), (2, '2º semestre')], default=1, verbose_name='Período')),
                ('situacao', models.CharField(choices=[('M', 'Montado'), ('A', 'Avaliado'), ('E', 'Encerrado')], default='M', max_length=1, verbose_name='Situação')),
                ('avaliacao', models.TextField(blank=True, null=True, verbose_name='Anotação')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sca.Aluno')),
            ],
            options={
                'managed': True,
                'db_table': 'plano',
            },
        ),
        migrations.CreateModel(
            name='PlanoFuturo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('periodo', models.PositiveSmallIntegerField(choices=[(1, '1º semestre'), (2, '2º semestre')], default=1, verbose_name='Período')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadd.Plano')),
            ],
            options={
                'managed': True,
                'db_table': 'plano_futuro',
            },
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('inicio', models.TimeField(verbose_name='Início')),
                ('local', models.CharField(max_length=50, verbose_name='Local')),
                ('situacao', models.CharField(choices=[('A', 'Agendada'), ('C', 'Cancelada'), ('E', 'Encerrada')], default='A', max_length=1, verbose_name='Situação')),
                ('tipo', models.CharField(choices=[('I', 'Informação'), ('C', 'Convocação')], default='I', max_length=1, verbose_name='Tipo')),
                ('anotacao', models.TextField(blank=True, null=True, verbose_name='Anotação')),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadd.Comissao')),
            ],
            options={
                'managed': True,
                'db_table': 'reuniao',
            },
        ),
        migrations.AddField(
            model_name='itemplanofuturo',
            name='planofuturo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadd.PlanoFuturo'),
        ),
        migrations.AddField(
            model_name='itemplanoatual',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadd.Plano'),
        ),
        migrations.AddField(
            model_name='convocacao',
            name='reuniao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadd.Reuniao'),
        ),
    ]
