# Generated by Django 2.0.4 on 2018-04-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='periodo',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Selecione o período'), (1, '1º semestre'), (2, '2º semestre')], default=1, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='periodo',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Selecione o período'), (1, '1º semestre'), (2, '2º semestre')], verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='itemhorario',
            name='diasemana',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Selecione o dia da semana'), (0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Semipresencial'), (8, 'Horário variável')], verbose_name='Dia da semana'),
        ),
        migrations.AlterField(
            model_name='itemhorario',
            name='fim',
            field=models.TimeField(null=True, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='itemhorario',
            name='inicio',
            field=models.TimeField(null=True, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='periodo',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Selecione o período'), (1, '1º semestre'), (2, '2º semestre')], default=1, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='situacao',
            field=models.CharField(choices=[(None, 'Selecione a situação'), ('M', 'Montado'), ('A', 'Avaliado'), ('E', 'Encerrado')], default='M', max_length=1, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='planofuturo',
            name='periodo',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Selecione o período'), (1, '1º semestre'), (2, '2º semestre')], default=1, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='situacao',
            field=models.CharField(choices=[(None, 'Selecione a situação'), ('A', 'Agendada'), ('C', 'Cancelada'), ('E', 'Encerrada')], default='A', max_length=1, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='tipo',
            field=models.CharField(choices=[(None, 'Selecione o tipo'), ('I', 'Informação'), ('C', 'Convocação')], default='I', max_length=1, verbose_name='Tipo'),
        ),
    ]
