# Generated by Django 2.0.4 on 2018-04-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadd', '0002_auto_20180428_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemhorario',
            name='fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='itemhorario',
            name='inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Início'),
        ),
    ]
