# Generated by Django 2.0.4 on 2018-06-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadd', '0003_auto_20180623_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocacao',
            name='envioemail',
            field=models.NullBooleanField(verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='convocacao',
            name='presente',
            field=models.NullBooleanField(verbose_name='Presente'),
        ),
    ]
