# Generated by Django 2.0.4 on 2018-04-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadd', '0003_auto_20180428_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reprovacurso8periodoslaranja', models.PositiveSmallIntegerField()),
                ('reprovademaiscursoslaranja', models.PositiveSmallIntegerField()),
                ('reprovacurso8periodosvermelha', models.PositiveSmallIntegerField()),
                ('reprovademaiscursosvermelha', models.PositiveSmallIntegerField()),
                ('qtdperiodoslaranja', models.CharField(max_length=10)),
                ('qtdperiodosvermelha', models.CharField(max_length=10)),
                ('maxcreditosporperiodopreta', models.PositiveSmallIntegerField()),
                ('defaultitensporpagina', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'parametros',
                'managed': True,
            },
        ),
    ]
