# Generated by Django 2.0.4 on 2018-06-24 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadd', '0004_auto_20180624_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='comissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadd.Comissao'),
        ),
    ]
