# Generated by Django 2.0.4 on 2018-04-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadd', '0004_parametros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='defaultitensporpagina',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Selecione o total de itens por página'), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50)]),
        ),
    ]
