# Generated by Django 2.0.4 on 2018-06-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadd', '0005_auto_20180429_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='maxcreditosporperiodo',
            field=models.PositiveSmallIntegerField(default=28),
        ),
        migrations.AlterField(
            model_name='documento',
            name='indice',
            field=models.FileField(max_length=50, upload_to='documentos/', verbose_name='Índice'),
        ),
    ]
