# Generated by Django 2.0.4 on 2018-06-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadd', '0007_auto_20180608_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemhorario',
            name='periodo',
            field=models.CharField(default=1, max_length=3, verbose_name='Período'),
        ),
    ]
